# Generated by Django 2.2.1 on 2019-06-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190601_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='token',
            field=models.CharField(default='', max_length=48),
            preserve_default=False,
        ),
    ]
