# Generated by Django 2.2.1 on 2019-06-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('project', 'endpoint')},
        ),
    ]
